### ISSUE TITLE
Spelling mistakes: "Enouph" and "atleast"

### ISSUE THREAD

**Issue by ExecutedGames** [TheBluestBluester/omegga-Base_wars#1]
![image](https://user-images.githubusercontent.com/29869269/184342773-866f8741-7d30-4bff-a8af-b0509666170c.png)

"Enouph". Also "atleast" should be spelled "at least". smh

**Comment by TheBluestBluester** [comment]
e

**Comment by TheBluestBluester** [comment]
fixdj
